markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : uPortal Korea
production_url : http://uportalkorea.github.io
comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

description: "uPortal Korea"
disqus_shortname: uPortal Korea
author :
  name : uPortal Korea
  github : uportalkorea
  twitter : uportalkorea
  email: uportal.kr@gmail.com

